id: operations/mediawiki-config
name: operations/mediawiki-config
shortName: Codereview stats for operations/mediawiki-config
format: csv
url: /data/datasources/gerrit-stats/datafiles/operations/mediawiki-config/mediawiki-config.csv

timespan:
    end: 2012/7/26
    start: 2012/2/25
    step: 1d

columns:
    labels:
    - Date
    - date
    - commits
    - self_review
    - time_first_review_staff
    - time_first_review_total
    - time_first_review_volunteer
    - time_plus2_staff
    - time_plus2_total
    - time_plus2_volunteer
    types:
    - date
    - int
    - int
    - int
    - int
    - int
    - int
    - int
    - int

chart:
    chartType: dygraphs
