id: operations_mediawiki-config_mediawiki-config
name: Codereview stats for operations/mediawiki-config repo
shortName: operations/mediawiki-config
format: csv
url: /data/datafiles/gs/operations/mediawiki-config/mediawiki-config.csv

timespan:
    end: 2012/8/28
    start: 2012/2/23
    step: 1d

columns:
    labels:
    - date
    - commits
    - self_review
    - waiting_first_review_staff
    - waiting_first_review_total
    - waiting_first_review_volunteer
    - waiting_plus2_staff
    - waiting_plus2_total
    - waiting_plus2_volunteer
    types:
    - date
    - int
    - int
    - int
    - int
    - int
    - int
    - int
    - int

chart:
    chartType: dygraphs
