id: mediawiki_extensions_CommunityApplications_CommunityApplications
name: Codereview stats for mediawiki/extensions/CommunityApplications repo
shortName: mediawiki/extensions/CommunityApplications
format: csv
url: /data/datafiles/gs/mediawiki/extensions/CommunityApplications/CommunityApplications.csv

timespan:
    end: 2012/9/10
    start: 2012/3/21
    step: 1d

columns:
    labels:
    - date
    - commits
    - self_review
    - waiting_first_review_staff
    - waiting_first_review_total
    - waiting_first_review_volunteer
    - waiting_plus2_staff
    - waiting_plus2_total
    - waiting_plus2_volunteer
    types:
    - date
    - int
    - int
    - int
    - int
    - int
    - int
    - int
    - int

chart:
    chartType: dygraphs
