id: operations/apache-config
name: operations/apache-config
shortName: Codereview stats for operations/apache-config
format: csv
url: /data/datasources/gerrit-stats/datafiles/operations/apache-config/apache-config.csv

timespan:
    end: 2012/7/27
    start: 2012/5/9
    step: 1d

columns:
    labels:
    - Date
    - date
    - commits
    - self_review
    - time_first_review_staff
    - time_first_review_total
    - time_first_review_volunteer
    - time_plus2_staff
    - time_plus2_total
    - time_plus2_volunteer
    types:
    - date
    - int
    - int
    - int
    - int
    - int
    - int
    - int
    - int

chart:
    chartType: dygraphs
