id: operations_apache-config
shortName: operations/apache-config
name: Codereview stats for operations/apache-config
format: csv
url: /data/datafiles/gerrit-stats/operations/apache-config/apache-config.csv

timespan:
    end: 2012/7/30
    start: 2012/5/9
    step: 1d

columns:
    labels:
    - date
    - commits
    - self_review
    - time_first_review_staff
    - time_first_review_total
    - time_first_review_volunteer
    - time_plus2_staff
    - time_plus2_total
    - time_plus2_volunteer
    types:
    - date
    - int
    - int
    - int
    - int
    - int
    - int
    - int
    - int

chart:
    chartType: dygraphs
