id: operations_apache-config_apache-config
name: Codereview stats for operations/apache-config repo
shortName: operations/apache-config
format: csv
url: /data/datafiles/gs/operations/apache-config/apache-config.csv

timespan:
    end: 2012/11/18
    start: 2012/5/8
    step: 1d

columns:
    labels:
    - date
    - commits
    - self_review
    - waiting_first_review_staff
    - waiting_first_review_total
    - waiting_first_review_volunteer
    - waiting_plus2_staff
    - waiting_plus2_total
    - waiting_plus2_volunteer
    types:
    - date
    - int
    - int
    - int
    - int
    - int
    - int
    - int
    - int

chart:
    chartType: dygraphs
