id: mediawiki_extensions_SimpleSecurity_SimpleSecurity
name: Codereview stats for mediawiki/extensions/SimpleSecurity repo
shortName: mediawiki/extensions/SimpleSecurity
format: csv
url: /data/datafiles/gs/mediawiki/extensions/SimpleSecurity/SimpleSecurity.csv

timespan:
    end: 2012/12/24
    start: 2012/10/21
    step: 1d

columns:
    labels:
    - date
    - commits
    - self_review
    - waiting_first_review_staff
    - waiting_first_review_total
    - waiting_first_review_volunteer
    - waiting_plus2_staff
    - waiting_plus2_total
    - waiting_plus2_volunteer
    types:
    - date
    - int
    - int
    - int
    - int
    - int
    - int
    - int
    - int

chart:
    chartType: dygraphs
